TrainerNames: ; 399ff (e:59ff)
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BUG MASTER@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "CHIEF@"
	db "BLACKBELT@"
	db "RIVAL@"
	db "SWIMMER@"
	db "ROCKET@"
	db "SCIENTIST@"
	db "BOSS@"
	db "ROCKET@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "BRUNO@"
	db "BROCK@"
	db "MISTY@"
	db "LT.SURGE@"
	db "ERIKA@"
	db "KOGA@"
	db "BLAINE@"
	db "SABRINA@"
	db "ACE TRAINER@"
	db "ACE TRAINER@"
	db "ELITE FOUR@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "GENTLEMAN@"
	db "RIVAL@"
	db "CHAMPION@"
	db "ELITE FOUR@"
	db "CHANNELER@"
	db "AGATHA@"
	db "LANCE@"
	db "ELITE FOUR@"
	db "ELITE FOUR@"
	db "HEX MANIAC@"
	db "TRAINER@"

